# Hiperparámetros y configuración del proyecto

# Data ingestion
data:
  tmdb_max_results: 1000
  omdb_batch_size: 50
  languages: ["es", "en"]

# Feature engineering
features:
  max_features: 5000
  ngram_range: [1, 3]
  min_df: 2
  max_df: 0.8

# Model training
model:
  test_size: 0.2
  val_size: 0.1
  random_state: 42
  algorithm: "random_forest"
  n_estimators: 100
  max_depth: 10

# Content triggers
triggers:
  dimensions:
    - violence
    - sexual_content
    - substance_abuse
    - suicide_self_harm
    - child_abuse
    - discrimination
    - strong_language
    - psychological_horror
    - animal_cruelty
  
  thresholds:
    low: 0.3
    medium: 0.6
    high: 0.8

# Scoring
scoring:
  weight_violence: 0.15
  weight_sexual: 0.15
  weight_substance: 0.10
  weight_suicide: 0.15
  weight_child_abuse: 0.15
  weight_discrimination: 0.10
  weight_language: 0.05
  weight_horror: 0.10
  weight_animal: 0.05
