FROM ghcr.io/mlflow/mlflow:v2.16.2

USER root

# Instalar psycopg2 para PostgreSQL y boto3 para S3 
RUN pip install --no-cache-dir \
    psycopg2-binary==2.9.9 \
    boto3==1.34.144

USER 1000

EXPOSE 5000
